name: "Auto Greeting for Issues and PRs"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Greet first-time contributors
        id: greet
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hi @${{ github.actor }}! Thanks for raising an issue on the neXtgen project. We’re thrilled to have you contribute! Please provide as much detail as possible to help us resolve the issue effectively.
            Welcome to neXtgen! 🌍📱😊
          pr-message: |
            👋 Hi @${{ github.actor }}! Thank you for your first pull request to the neXtgen project! 🎉 Awesome job contributing to our platform, and we appreciate your effort. We’ll review it soon. Keep up the fantastic work! 🚀

      - name: Assign issue or pull request to a team member
        if: github.event_name == 'issues' || github.event_name == 'pull_request_target'
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number || github.event.pull_request.number }}
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"assignees":["team-member-username"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}"

      - name: Welcome message for community contributors
        if: github.event_name == 'issues' || github.event_name == 'pull_request_target'
        uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Hi @${{ github.actor }}! Thanks for opening this issue on neXtgen. Our team will check it out soon. Keep contributing! 🌟"
          pr-message: "🎉 Way to go, @${{ github.actor }}! Thank you for your pull request. Our team will review it shortly. 🚀"
